





















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `CitaTallerAzure`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=tcp:kmrsha0ybe.database.windows.net,1433;Database=citataller;User ID=webapi@kmrsha0ybe;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace WebAPI.ServiceModel
{
    public partial class Dms : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        public string DomainUrl { get; set;}
        public short? Idioma { get; set;}
    }
    public partial class DmsCortesia : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public Guid DmsId { get; set;}
        public string Descripcion { get; set;}
        public string DmsKey { get; set;}
    }
    public partial class DmsJob : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public Guid DmsId { get; set;}
        public string Descripcion { get; set;}
    }
    public partial class DmsTaller : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public Guid DmsId { get; set;}
        public string Descripcion { get; set;}
        public string Direccion { get; set;}
        public bool? VehiculoCortesia { get; set;}
        public string DmsKey { get; set;}
    }
    public partial class Solicitud : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        public DateTime? CreacionFecha { get; set;}
        public Guid? CreacionDevice { get; set;}
        public string Numgsm { get; set;}
        public string Email { get; set;}
        public Guid? DmsCortesiaId { get; set;}
        public string Nombre { get; set;}
        public string Apellidos { get; set;}
        public string Matric { get; set;}
        public string Chasis { get; set;}
        [Required]
        public Guid DmsTallerId { get; set;}
        public string Descripcion { get; set;}
        public bool? VehiculoCortesia { get; set;}
        public bool? DmsCitaCreada { get; set;}
        public string DmsClienteKey { get; set;}
        public string DmsVehiculoKey { get; set;}
        public string DmsCitaKey { get; set;}
    }
    public partial class SolicitudHora : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public Guid SolicitudId { get; set;}
        public DateTime? Fecha { get; set;}
        public byte? Hora { get; set;}
        public byte? Minuto { get; set;}
    }
    public partial class SolicitudJob : IHasId<Guid> 
    {
        [Alias("Id")]
        [Required]
        public Guid Id { get; set;}
        [Required]
        public Guid SolicitudId { get; set;}
        [Required]
        public Guid DmsJobId { get; set;}
    }
}
#pragma warning restore 1591


